### ISSUE TITLE
setTimeout call is not working

### ISSUE THREAD

**Issue by s-nadesh** [pawnesh/family_tree#3]
Hi, I used newway folder.

In my html file, I call the function like this 

setTimeout(function() {
   var family_mem = [];
   family_mem.push({id: 0, name: "test one", gender: "M", age: "34", pic: "img/profile.png"});
   var pkFamily = $('#pk-family-tree').pk_family({referenceVar:'pkFamily', family: family_mem});
}, 1000); 

Tree generated successfully, but prototype functions are not working.

**Error msg in my console**
Uncaught ReferenceError: pkFamily is not defined
    at HTMLAnchorElement.onclick

Kindly help me.

**Comment by pawnesh** [comment]
​ok let me check that, I will reply with solution as soon as possible.​

*Best Regards*
Pawnesh Rai

**Comment by s-nadesh** [comment]
Okay. Thank you.

**Comment by pawnesh** [comment]
Please update the ps-family.js file at your local copy from the newway folder. I forget to disable the default initialization of family tree. It will work now!

**Comment by s-nadesh** [comment]
Hi still the same problem.. 

I downloaded your latest code. and In the index.html instead of your code, I used the below code

setTimeout(function () {
           var family_mem = [];
           family_mem.push({id: 0, name: "test one", gender: "M", age: "34", pic: "img/profile.png"});
           var pkFamily = $('#pk-family-tree').pk_family({referenceVar: 'pkFamily', family: family_mem});
}, 1000);

Tree generated successfully with the given **family_mem** array, but prototype functions are not working.

**Error msg in my console**
Uncaught ReferenceError: pkFamily is not defined
at HTMLAnchorElement.onclick

Kindly help me.

**Comment by pawnesh** [comment]
It is not happening from my end. hard to recreate the bug, if you can share a test url with your code I may figure it out what is the reason. are you using any other plugin.

**Comment by s-nadesh** [comment]
Below are the steps I did.

1) I downloaded your zip folder, and extract it in my local system.
2) Then I opened the **index.html** file inside the **newway** folder.
3) Instead of your code, I used the below code in the index.html file, 
<script>
setTimeout(function () {
    var family_mem = [];
    family_mem.push({id: 0, name: "test one", gender: "M", age: "34", pic: "img/profile.png"});
    var pkFamily = $('#pk-family-tree').pk_family({referenceVar: 'pkFamily', family: family_mem});
}, 1000);
 </script>
4) Now I opened your html file in browser, the tree was generated successfully. But when i click the image, openMenu function is not working. Check the below image.
![screenshot from 2017-05-08 12 37 41](https://cloud.githubusercontent.com/assets/8857848/25793812/d356d070-33eb-11e7-8907-f0bdf3f486a1.png)

**Comment by pawnesh** [comment]
var pkFamily = null;
            setTimeout(function() {
var family_mem = [];
family_mem.push({id: 0, name: "test one", gender: "M", age: "34", pic: "img/profile.png"});
pkFamily = $('#pk-family-tree').pk_family({referenceVar:'pkFamily', family: family_mem});
}, 1000);


do this

**Comment by s-nadesh** [comment]
It is working, Thank you so much.
