### ISSUE TITLE
More than one spouse

### ISSUE THREAD

**Issue by shaikhather** [pawnesh/family_tree#4]
I found that we cannot add more than one spouse. as in our religion it is allowed to have 4 at the same time. Also the children are related to mother and father both, so the children will also required to updated as a test case:
1 Husband has 2 Wives.
display should chanaged , one wife at left and other on right. if it 4 wives then 2 on left and 2 on right or like star. then children connection should be according to the mother and father both. when a person add a child , then he should select mother and father both at the same time to make proper relation.

hope you understand the scenario.
thanks.
Shaikh Ather

**Comment by pawnesh** [comment]
Yes I know that, it is under consideration to add multiple mother and father. I will add this feature too when I will get time. Or if you are interested you can contribute :)
