### ISSUE TITLE
save_family.php  file is  still missing .

### ISSUE THREAD

**Issue by shraddhaparab** [pawnesh/family_tree#9]
Hello,
as you said you have added it,but still it is not getting.
The send button is not working, like entered data not getting sent. because on send button click save_family.php file gets called.which you have not added in a project.
can you please guide me.

Thanks.

**Comment by shraddhaparab** [comment]
Yes,I got the save_family.php file but its not working.

**Comment by shraddhaparab** [comment]
on send button click,no operation is performing,it should send/add entered data to the database.
what is database structure ?

**Comment by shraddhaparab** [comment]
Hello,

I shifted the project from local PC to server and kept the same post method and url.
on 'send data' button click ,I am getting the alert as 'completed' but as per written in save_family.php that is print_r($tree) , so it should print the tree data but nothing is displayed.

Thanks.

**Comment by pawnesh** [comment]
1. You have to check the console for checking what is the data structure.
2. Regarding database structure: I made a jQuery plug-in not a family tree application. It is your job to find out what to do with data received at save_family.php

**Comment by pawnesh** [comment]
![help](https://user-images.githubusercontent.com/7032266/40463529-6d7ff082-5f33-11e8-9ab5-8c77a946c426.png)
This is most I can help you.
